# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         uncpan
version:      1.00
version_from: uncpan
installdirs:  site
requires:
    Archive::Tar:                  Archive::Zip
    File::Spec:                    File::Basename
    Getopt::Std:                   IO::Dir

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
